from pydantic import Field, field_validator
from typing import List, Literal
from ..base import BaseModelWithItem

Refs = List[List[List[str]]]

class PropertyModel(BaseModelWithItem):
    """Represents a property with name, type, and key information"""
    name: str = Field(..., description="Property name")
    type: str = Field(..., description="Property type")
    isKey: bool = Field(..., description="Whether this property is a primary key")
    refs: Refs = Field(..., description="Source reference from the functional requirements")

class CommandActionIds(BaseModelWithItem):
    """Represents the IDs section of a command action"""
    aggregateId: str = Field(..., description="ID of the target aggregate")
    commandId: str = Field(..., description="ID of the command")

class EventActionIds(BaseModelWithItem):
    """Represents the IDs section of an event action"""
    aggregateId: str = Field(..., description="ID of the target aggregate")
    eventId: str = Field(..., description="ID of the event")

class ReadModelActionIds(BaseModelWithItem):
    """Represents the IDs section of a read model action"""
    aggregateId: str = Field(..., description="ID of the target aggregate")
    readModelId: str = Field(..., description="ID of the read model")

class CommandArgs(BaseModelWithItem):
    """Arguments for command actions"""
    commandName: str = Field(..., description="Name of the command")
    commandAlias: str = Field(..., description="Display alias for the command")
    api_verb: Literal["POST", "PUT", "DELETE"] = Field(..., description="HTTP verb for the command (must be POST, PUT or DELETE — queries belong to readModelActions)")
    properties: List[PropertyModel] = Field(..., description="List of command properties")
    outputEventIds: List[str] = Field(..., description="List of event IDs generated by this command")
    actor: str = Field(..., description="Actor role(Can be User, System, Admin, etc.)")
    refs: Refs = Field(..., description="Source reference from the functional requirements")

    @field_validator("api_verb", mode="before")
    @classmethod
    def _normalize_api_verb(cls, value):
        """허용되지 않은 HTTP verb 를 보정한다.

        LLM 이 조회성 커맨드에 'GET' 을 넣는 사례가 반복되는데, Literal 검증에 걸리면
        pydantic 이 응답 '전체'를 거부한다. 그 결과 나머지 정상 커맨드 12개까지 버려지고
        재시도도 같은 이유로 실패해, Aggregate 하나가 통째로 비는 문제가 있었다
        ('구독' Aggregate 사례 — 두 번의 생성에서 동일하게 재현).

        의미상 조회는 ReadModel 이 맡아야 하지만, 여기서 액션을 버리는 것보다
        생성해두고 사용자가 화면에서 고치게 하는 편이 낫다.
        """
        if not isinstance(value, str):
            return value

        normalized = value.strip().upper()
        if normalized in ("POST", "PUT", "DELETE"):
            return normalized

        # 조회/헤더성 verb → 부작용 없는 기본값으로 강등
        if normalized in ("GET", "HEAD", "OPTIONS"):
            return "POST"
        if normalized == "PATCH":
            return "PUT"

        return "POST"

class EventArgs(BaseModelWithItem):
    """Arguments for event actions"""
    eventName: str = Field(..., description="Name of the event")
    eventAlias: str = Field(..., description="Display alias for the event")
    properties: List[PropertyModel] = Field(..., description="List of event properties")
    refs: Refs = Field(..., description="Source reference from the functional requirements")

class ReadModelArgs(BaseModelWithItem):
    """Arguments for read model actions"""
    readModelName: str = Field(..., description="Name of the read model")
    readModelAlias: str = Field(..., description="Display alias for the read model")
    isMultipleResult: bool = Field(..., description="Whether the read model returns multiple results")
    queryParameters: List[PropertyModel] = Field(..., description="List of query parameters")
    actor: str = Field(..., description="Actor role(Can be User, System, Admin, etc.)")
    refs: Refs = Field(..., description="Source reference from the functional requirements")

class CommandAction(BaseModelWithItem):
    """Represents a command action"""
    actionName: str = Field(..., description="Name of the action")
    objectType: Literal["Command"] = Field(..., description="Type of object (always 'Command')")
    ids: CommandActionIds = Field(..., description="ID information for the action")
    args: CommandArgs = Field(..., description="Arguments for the command")

class EventAction(BaseModelWithItem):
    """Represents an event action"""
    actionName: str = Field(..., description="Name of the action")
    objectType: Literal["Event"] = Field(..., description="Type of object (always 'Event')")
    ids: EventActionIds = Field(..., description="ID information for the action")
    args: EventArgs = Field(..., description="Arguments for the event")

class ReadModelAction(BaseModelWithItem):
    """Represents a read model action"""
    actionName: str = Field(..., description="Name of the action")
    objectType: Literal["ReadModel"] = Field(..., description="Type of object (always 'ReadModel')")
    ids: ReadModelActionIds = Field(..., description="ID information for the action")
    args: ReadModelArgs = Field(..., description="Arguments for the read model")

class CreateCommandActionsByFunctionOutput(BaseModelWithItem):
    """Output model for creating command actions by function with structured reasoning and results"""
    commandActions: List[CommandAction] = Field(..., description="List of command actions to be generated")
    eventActions: List[EventAction] = Field(..., description="List of event actions to be generated")
    readModelActions: List[ReadModelAction] = Field(..., description="List of read model actions to be generated")